<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Promise</title>
</head>
<body>
<script>
	// const 摇塞子 = () => {
	// 	return new Promise((resolve, reject) => {
	// 		setTimeout(() => {
	// 			resolve(parseInt(Math.random() * 6) + 1)
	// 		}, 1000)
	// 	})
	// }
	// 摇塞子().then(result => console.log(result))


	// const 摇色子 = () => {
	// 	return new Promise((resolve, reject) => {
	// 		resolve(4)
	// 	})
	// }
	// //1 4 2
	// setTimeout(() => console.log(2),0)
	// 摇色子().then(n => console.log(n))
	// console.log(1);

	/*Promise.resolve(result)可以制造一个成功（或失败）*/
	// const 摇色子 = () => {
	// 	return Promise.resolve(new Promise((resolve, reject) => {
	// 		reject('失败了')
	// 	}))
	// }
	// 摇色子().then(res => console.log(res)) //Uncaught (in promise) 失败了

	/*Promise.resolve(reason)可以制造一个失败*/
	// Promise.reject('我错了').then(null, reason => console.log(reason))  //我错了


	Promise.all([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)])
		.then(values => console.log(values)) // [1, 2, 3]
	Promise.all([Promise.reject(1), Promise.resolve(2), Promise.resolve(3)])  // Promise.all()只要有一个失败，就只会返回第一个失败的结果
		.then(values => console.log(values), reason => console.log(reason)) // 1
	Promise.allSettled([Promise.reject(1), Promise.reject(2), Promise.resolve(3)]) // Promise.allSettled()会返回所有成功和失败的结果，但是兼容性太差，在stage-4阶段
		.then(values => console.log(values)) //  [{status: "rejected", reason: 1},{status: "rejected", reason: 2},{status: "fulfilled", value: 3}]
</script>
</body>
</html>